chore: Update dependencies
munshkr/flok pull request #160
Opened 2023-01-02 23:45 UTC by jordan-ms

This commit updates the dependencies for flok-core. It also updates the project to use the latest version of yarn. The only code changes, which are minor, update types within flok-core to be TypeScript interfaces.

I also pinned flak-core's `prettier` version to an exact micro version, since this is the recommended practice according to the prettier docs.

2023-01-02 23:47 UTC, jordan-ms commented
@munshkr Came across this project while watching a video on hydra.js. Thought I'd lend a hand. Could you please review this PR when you have time? I'd be happy to help with upgrading dependencies for the other packages too.

2023-01-14 14:01 UTC, munshkr requested changes
Hey! Thank you so much for contributing, I really appreaciate it. The only thing I'd change is the package version change, otherwise everything looks good!

2023-01-14 20:30 UTC, jordan-ms commented on packages/core/package.json
> +  "version": "1.0.0",
Sounds good to me! I can make those changes right now.

2023-01-14 20:37 UTC, jordan-ms commented on packages/core/package.json
> +  "version": "1.0.0",
Alrighty. Bumped the patch version in this commit: 7dbe9a5

2023-01-24 02:39 UTC, munshkr approved these changes

2023-01-24 02:39 UTC, merged

2023-01-24 02:40 UTC, munshkr commented
Thanks!